name: "deploy-git"
description: "Deploy a project using Git"
author: "Demurgos"
branding:
  icon: share
  color: black
inputs:
  accessToken:
    description: |
      Personal access token with. The token requires the `public_repo` scope
      (read/write access to public repositories of the user).
      See https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line
    required: true
  srcBranch:
    description: "Source branch. Default: branch that triggered the workflow."
      required: false
  srcDir:
    description: "Directory in the source branch containing the files to deploy. Default: `.`"
    required: false
    default: "."
  destBranch:
    description: "Destination branch: the files will be deployed at its root."
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
